### ISSUE TITLE
windows virtualbox cygwin symlink not showing in VM

### ISSUE THREAD

**Issue by OCCCFG** [winnfsd/vagrant-winnfsd#124]
VirtualBox 5.2.4
Vagrant 2.0.2
vagrant-winnfsd 1.4.0
Folder sharing from the host to the guest configured using winnfsd plugin, which works nicely except, so far, for symlinks created outside the VM

outside vm:
# ln -s ../vendor/behat/behat/behat ./behat
# ls -l
behat -> ../vendor/behat/behat/bin/behat

inside vm:
# ls -l
?rwxrwxrwx 1 root root  76 May 16 06:34 behat

Executing behat inside in the vm responds with
No such device or address

It is understood why the error occurs because the symbolic link is not recognised inside the VM, hence the (?) question mark next the file permission bits.

This means the symbolic links would need to be created inside the VM, which would not work for our setup. We need symbolic links that are configured outside the VM to work inside the VM

Many thanks,
CFG

**Comment by marcharding** [comment]
That is because cygwin symlink are no ntfs symlinks. They are a special binary format which only works within cygwin. Try for yourself, the symlinks from cygwin won't work in explorer.

The solution is simple, create your symlinks the windows way with mklink in an elevated cmd.exe.

`mklink  behat ..\vendor\behat\behat\behat `

(notice the swiched parameter order target source)

Also remember to run vagrant/winnfsd with elevated rights so symlink can be created from within vagrant too.
